
// Sign up
POST http://localhost:3001/user/signup
content-type: application/json

{
    "username": "John",
    "email": "john@abc.com",
    "password": "213bhett4956469"
}

###

// Login
POST http://localhost:3001/user/login
content-type: application/json

{
    "email": "john@abc.com",
    "password": "213bhett4956469"
}

###

// Fetching user from token after signup/login
GET http://localhost:3001/user/me
content-type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRiNTI4YjQ0NDkwZjQ3MTIxMjlmZDVlIn0sImlhdCI6MTY4OTU5NDM0NiwiZXhwIjoxNjg5NTk3OTQ2fQ._oykvtBYphIOEw0b81AdV4bjb70Hanu9WW3MyJKDKpU